### PR TITLE
Update activity

### PR DESCRIPTION
**Pull request by sparshg**
@tchx84 I have no idea why the are cards not getting rendered, the activity works if I launch it natively but boxes are not rendered in the flatpak. I looked into the activity, the cards are generating but not getting displayed. I tried a few changes like using `.show()` on cards or setting a single card as a child in the table but that didn't work too. @chimosky Any ideas what could be wrong here?

### CODE REVIEW

**Review by tchx84 — CHANGES_REQUESTED** [review]
@sparshg please keep in mind the debugging tecniques that I have taught you before.

1. Like I mentioned before, **do not** just post "this doesn't work" and disappear.
2. Since the same code **is working** on the previous flatpak version, try change one dependency at a time to detect what exactly is triggering this breakage.
3. Once you have identified what change breaks it, study the code to come up with minimum example that reproduces the issue.

If you follow those steps you will certainly understand what's going on here.

There are other basic things you can do like examining the output errors. In this particular case, it's pretty explicit if you run the Flatpak from the terminal:

```
1691075521.654568 ERROR root: Read: Error parsing file 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
1691075521.654660 ERROR root:  Reading setup file /app/share/sugar/activities/Memorize.activity/demos/addition.zip
Traceback (most recent call last):
  File "/app/share/sugar/activities/Memorize.activity/cardtable.py", line 226, in key_press_event
    x = self.selected_card[0]
AttributeError: 'CardTable' object has no attribute 'selected_card'
```

CCing @chimosky here so he can monitor your progress as well.

**Comment by sparshg** [comment]
Uhh okay I didn't get those logs... There was something weird going on, it didn't work without my changes of this PR too when I tried to revert back.

It took me long to figure out this is probably due to the saved state of activity from previous build that the new build is getting resumed from and hence it got really confusing. I tried messing around inside the activity and was able to reset the cards. (I did this on a build with latest upstream commit).

The error you were getting due to which cards weren't showing is an unrelated issue whose fix is already there in upstream. I have created a PR to update the version so we can include that change.

How can I avoid this? like flushing out the saved state of activity while installing new build? Uninstalling previous build doesn't work either.

> Like I mentioned before, do not just post "this doesn't work" and disappear.

Sorry I was just totally confused on this one and had already spent lots of time to debug this. I thought its better to wait a bit and get a nudge in the right direction instead of wasting time further on the same activity. If you hadn't provided those logs it wouldn't have struck me this could be related to saved state of activity.

**Comment by sparshg** [comment]
The bug I was facing due to which cards didn't appear until I changed game mode is https://github.com/sugarlabs/memorize-activity/issues/34. 

Trying to debug in upstream.

Fixed https://github.com/sugarlabs/memorize-activity/pull/36

**Comment by tchx84** [comment]
> Uhh okay I didn't get those logs... There was something weird going on, it didn't work without my changes of this PR too when I tried to revert back.
> 
> It took me long to figure out this is probably due to the saved state of activity from previous build that the new build is getting resumed from and hence it got really confusing. I tried messing around inside the activity and was able to reset the cards. (I did this on a build with latest upstream commit).
> 
> The error you were getting due to which cards weren't showing is an unrelated issue whose fix is already there in upstream. I have created a PR to update the version so we can include that change.
> 
> How can I avoid this? like flushing out the saved state of activity while installing new build? Uninstalling previous build doesn't work either.
> 

The proper solution would be to make the app understand that it is an older version state and migrate it, but it would also be acceptable to make it just not break the app.

> > Like I mentioned before, do not just post "this doesn't work" and disappear.
> 
> Sorry I was just totally confused on this one and had already spent lots of time to debug this. I thought its better to wait a bit and get a nudge in the right direction instead of wasting time further on the same activity. If you hadn't provided those logs it wouldn't have struck me this could be related to saved state of activity.

**Comment by tchx84** [comment]
> The bug I was facing due to which cards didn't appear until I changed game mode is [sugarlabs/memorize-activity#34](https://github.com/sugarlabs/memorize-activity/issues/34).
> 
> Trying to debug in upstream.
> 
> Fixed [sugarlabs/memorize-activity#36](https://github.com/sugarlabs/memorize-activity/pull/36)

I tested the latest build from the PR, reset the autosave files, e.g. `rm -rf /var/home/tchx84/.var/app/org.sugarlabs.Memorize`, but I am still getting this error
```
Traceback (most recent call last):
  File "/app/share/sugar/activities/Memorize.activity/cardtable.py", line 226, in key_press_event
    x = self.selected_card[0]
AttributeError: 'CardTable' object has no attribute 'selected_card'

```

**Comment by sparshg** [comment]
> The error you were getting due to which cards weren't showing is an unrelated issue whose fix is already there in upstream.

My bad its not in the upstream. I still didn't encounter the error you are facing, neither in flatpak nor while running natively. But I did some changes in my PR in the upstream since some things were incorrect.

To be sure its not related to my system I installed the flatpak in a new Ubuntu 22.04 VM using the following command which tests my PR in the upstream. There were no errors.

> Build [57589 successful](https://buildbot.flathub.org/#/builders/6/builds/57589) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/40213/org.sugarlabs.Memorize.flatpakref
> ```

Can you test this latest build? and when exactly do we see the error you mentioned? Thanks. I will add data-checker once its merged in upstream.

**Comment by tchx84** [comment]
> Can you test this latest build? and when exactly do we see the error you mentioned? Thanks. I will add data-checker once its merged in upstream.

This branch works well, **if** I delete the current save file.

**Comment by sparshg** [comment]
Added the fix as patch, the fix is that if we clear all the cards and play the game, a demo game will be loaded. 

This led to confusion previously because I cleared all the cards in the previous build, and the new build resumed from previous state, which made me think that there was a problem in the current version.

I will add data checker once the new release is made in upstream soon

**Comment by sparshg** [comment]
Patches have been merged in upstream, I will update this as soon as we get the version bump too

**Review by tchx84 — APPROVED** [review]
good work!

**Pull request merged**
